### ISSUE TITLE
preferSimple setting has opposite effect

### ISSUE THREAD

**Issue by thailyn** [emipa606/PawnsChooseResearch#2]
This issue is in regards to the following code block:
https://github.com/emipa606/PawnsChooseResearch/blob/2e5d49c389ea6215b02a11ab3c4e5b94ef41ecea/Source/PawnsChooseResearch/ResearchPreferences.cs#L33-L38

The `num` variable here stores the pawn's preference score, and a higher value equates to more of a preference. However, due to the condition in the `if` statement, the quotient being subtracted from `num` will always be negative, and since this value is subtracted from `num`, `num` will always be increased as a result of entering the `if` block. Based on how the "prefer simple" / "Avoid Too Advanced Research" setting is described, a pawn would have a lower preference for a more advanced tech, but the opposite is happening.

**Comment by emipa606** [comment]
Ill fix it with a change of
`Faction.OfPlayerSilentFail.def.techLevel - researchProject.techLevel`
to 
`researchProject.techLevel - Faction.OfPlayerSilentFail.def.techLevel`
to get a positive value instead.
