### ISSUE TITLE
The number of research projects considered can not be changed and is rather small

### ISSUE THREAD

**Issue by thailyn** [emipa606/PawnsChooseResearch#3]
During the process for selecting a research project based on pawn preferences, only a small number of "candidate" research projects are considered. Specifically, it is not the case that every research project that can be presently researched are evaluated to find a pawn's favorite. It is probably not a good idea performance-wise to evaluate *every* research project, but the two issues I see are: 1) this artificial limitation is not mentioned anywhere in the mod description or in the in-game settings, and 2) the value can not be changed by the player.

How research projects are selected for consideration is slightly different when looking for a single pawn's project and the group project.

---

Selecting candidates for a single pawn's project is handled here:
https://github.com/emipa606/PawnsChooseResearch/blob/2e5d49c389ea6215b02a11ab3c4e5b94ef41ecea/Source/PawnsChooseResearch/SetResearch.cs#L12-L21

After this loop, the `list` variable will contain at most 4 research project defs, and those are later evaluated to get preference scores.

---

Finding a group research project is handled here:
https://github.com/emipa606/PawnsChooseResearch/blob/2e5d49c389ea6215b02a11ab3c4e5b94ef41ecea/Source/PawnsChooseResearch/SetResearch.cs#L74-L82

This selects a number of research projects that is, at most, equal to 1 + the number of pawns assigned to research work.

---

In my opinion, especially for selecting a single pawn's project, the number of research projects considered is very small. I think it would be best if both of these situation could be configured in the mod settings, and perhaps also use larger default values. In big modpacks with potentially 100 or more available research projects, there is a high chance for getting effectively random research projects being worked on, not one that fits the pawn's preferences.

**Comment by emipa606** [comment]
Perhaps it should be set to 10% of the amount of total research-projects for example?

**Comment by emipa606** [comment]
Changed it to 10 (or all if lower) projects that the pawn will actually want to do instead.
For groups changed to 20 + amount of pawns since I cant filter out projects before checking each pawn
