### ISSUE TITLE
Selecting a group research project does not properly use preference scores.

### ISSUE THREAD

**Issue by thailyn** [emipa606/PawnsChooseResearch#4]
Regarding the block of code here, which is part of selecting a group research project:
https://github.com/emipa606/PawnsChooseResearch/blob/2e5d49c389ea6215b02a11ab3c4e5b94ef41ecea/Source/PawnsChooseResearch/SetResearch.cs#L84-L105

The variable `num3`, which tracks the running preference score tally for the current research project being evaluated (`item2`), is not being reset each iteration of the outer loop (really, it should be local to the outer loop, not the entire function), so in virtually every situation, only the last research project evaluated (that is, a random one) will be chosen when selecting a group research project.

(The latest would not be selected only if the combined preference for the latest research project across all pawns is negative, which would only happen if most/all find that research project abhorrent or are incapable of researching it.)

**Comment by emipa606** [comment]
Ill move the `num3` to the inner loop to fix it. Also renamed the variables to be more descriptive.
